/****************************************************************************
 * boards/arm/stm32/stm32f407-custom/include/board.h
 *
 * SPDX-License-Identifier: Apache-2.0
 ****************************************************************************/

#ifndef __BOARDS_ARM_STM32_STM32F407_CUSTOM_INCLUDE_BOARD_H
#define __BOARDS_ARM_STM32_STM32F407_CUSTOM_INCLUDE_BOARD_H

#include <nuttx/config.h>

#ifndef __ASSEMBLY__
#  include <stdint.h>
#  include <stdbool.h>
#endif

/* Clocking: 8MHz HSE -> PLL -> 168MHz SYSCLK
 * APB1 = 42MHz, APB2 = 84MHz
 */

#define STM32_BOARD_XTAL        8000000ul
#define STM32_HSI_FREQUENCY     16000000ul
#define STM32_LSI_FREQUENCY     32000
#define STM32_HSE_FREQUENCY     STM32_BOARD_XTAL
#define STM32_LSE_FREQUENCY     32768

/* PLL: (8MHz/8)*336/2 = 168MHz SYSCLK, PLLQ=7 for 48MHz USB/SDIO */

#define STM32_PLLCFG_PLLM       RCC_PLLCFG_PLLM(8)
#define STM32_PLLCFG_PLLN       RCC_PLLCFG_PLLN(336)
#define STM32_PLLCFG_PLLP       RCC_PLLCFG_PLLP_2
#define STM32_PLLCFG_PLLQ       RCC_PLLCFG_PLLQ(7)

#define STM32_SYSCLK_FREQUENCY  168000000ul
#define STM32_HCLK_FREQUENCY    168000000ul
#define STM32_PCLK1_FREQUENCY   42000000ul
#define STM32_PCLK2_FREQUENCY   84000000ul

/* AHB/APB prescaler register values */

#define STM32_RCC_CFGR_HPRE     RCC_CFGR_HPRE_SYSCLK   /* HCLK  = SYSCLK / 1 */
#define STM32_RCC_CFGR_PPRE1    RCC_CFGR_PPRE1_HCLKd4  /* PCLK1 = HCLK / 4   */
#define STM32_RCC_CFGR_PPRE2    RCC_CFGR_PPRE2_HCLKd2  /* PCLK2 = HCLK / 2   */

/* Timer clocks: APB1 timers = 84MHz, APB2 timers = 168MHz */

#define STM32_APB1_TIM2_CLKIN   (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM3_CLKIN   (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM4_CLKIN   (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM5_CLKIN   (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM6_CLKIN   (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM7_CLKIN   (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM12_CLKIN  (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM13_CLKIN  (STM32_PCLK1_FREQUENCY * 2)
#define STM32_APB1_TIM14_CLKIN  (STM32_PCLK1_FREQUENCY * 2)

#define STM32_APB2_TIM1_CLKIN   (STM32_PCLK2_FREQUENCY * 2)
#define STM32_APB2_TIM8_CLKIN   (STM32_PCLK2_FREQUENCY * 2)
#define STM32_APB2_TIM9_CLKIN   (STM32_PCLK2_FREQUENCY * 2)
#define STM32_APB2_TIM10_CLKIN  (STM32_PCLK2_FREQUENCY * 2)
#define STM32_APB2_TIM11_CLKIN  (STM32_PCLK2_FREQUENCY * 2)

/* LED 配置
 * LED1=PD0(人体在位), LED2=PD1(坐姿告警), LED3=PD2(蓝牙状态) - 高电平点亮
 * LED4=PA1 - 低电平点亮
 */

#define GPIO_LED1  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                    GPIO_OUTPUT_CLEAR|GPIO_PORTD|GPIO_PIN0)
#define GPIO_LED2  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                    GPIO_OUTPUT_CLEAR|GPIO_PORTD|GPIO_PIN1)
#define GPIO_LED3  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                    GPIO_OUTPUT_CLEAR|GPIO_PORTD|GPIO_PIN2)
#define GPIO_LED4  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                    GPIO_OUTPUT_SET|GPIO_PORTA|GPIO_PIN1)

#define BOARD_LED1        0
#define BOARD_NLEDS       4
#define BOARD_LED1_BIT    (1 << BOARD_LED1)
#define BOARD_LED2_BIT    (1 << 1)
#define BOARD_LED3_BIT    (1 << 2)
#define BOARD_LED4_BIT    (1 << 3)

/* Button: PA0 = USER (active low, external pull-up) */

#define BUTTON_USER        0
#define NUM_BUTTONS        1
#define GPIO_BTN_USER      (GPIO_INPUT|GPIO_PULLUP|GPIO_EXTI|GPIO_PORTA|GPIO_PIN0)
#define BUTTON_USER_BIT    (1 << BUTTON_USER)

/* SPI1: PA5=SCK, PA6=MISO, PA7=MOSI (AF5) */

#define GPIO_SPI1_SCK     GPIO_SPI1_SCK_1
#define GPIO_SPI1_MISO    GPIO_SPI1_MISO_1
#define GPIO_SPI1_MOSI    GPIO_SPI1_MOSI_1

/* I2C1: PB6=SCL, PB7=SDA (AF4) - SHT30 + VL53L0X */

#define GPIO_I2C1_SCL     GPIO_I2C1_SCL_1
#define GPIO_I2C1_SDA     GPIO_I2C1_SDA_1

/* UART4: PC10=TX, PC11=RX (AF8) - BLE */

#define GPIO_UART4_TX     GPIO_UART4_TX_1
#define GPIO_UART4_RX     GPIO_UART4_RX_1

/* SDIO: SDIOCLK=48MHz, SDIO_CK=SDIOCLK/(118+2)=400KHz 初始化 */

#define SDIO_INIT_CLKDIV        (118 << SDIO_CLKCR_CLKDIV_SHIFT)

/* SDIO 传输时钟: DMA ON 16MHz, DMA OFF 12MHz */

#ifdef CONFIG_SDIO_DMA
#  define SDIO_MMCXFR_CLKDIV    (1 << SDIO_CLKCR_CLKDIV_SHIFT)
#  define SDIO_SDXFR_CLKDIV     (1 << SDIO_CLKCR_CLKDIV_SHIFT)
#else
#  define SDIO_MMCXFR_CLKDIV    (2 << SDIO_CLKCR_CLKDIV_SHIFT)
#  define SDIO_SDXFR_CLKDIV     (2 << SDIO_CLKCR_CLKDIV_SHIFT)
#endif

/* USART1: PA9=TX, PA10=RX (AF7) - 调试串口 */

#define GPIO_USART1_TX    GPIO_USART1_TX_2
#define GPIO_USART1_RX    GPIO_USART1_RX_2

/* USART2: PA2=TX, PA3=RX (AF7) - LD2410B */

#define GPIO_USART2_TX    GPIO_USART2_TX_1
#define GPIO_USART2_RX    GPIO_USART2_RX_1

/* USART3: PB10=TX, PB11=RX (AF7) - SU-03T */

#define GPIO_USART3_TX    GPIO_USART3_TX_1
#define GPIO_USART3_RX    GPIO_USART3_RX_1

/* SDIO DMA: Channel 4, Stream 3 */

#define DMAMAP_SDIO DMAMAP_SDIO_1

/* ===== GC9A01 LCD 显示屏控制引脚 ===== */

/* LCD_CS=PB3, LCD_DC=PD7, LCD_RST=PB5 */

#define GPIO_GC9A01_CS   (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                          GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN3)
#define GPIO_GC9A01_DC   (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                          GPIO_OUTPUT_CLEAR|GPIO_PORTD|GPIO_PIN7)
#define GPIO_GC9A01_RST  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                          GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN5)

/* ===== W25Q Flash 片选引脚 ===== */

/* W25Q_CS=PA15 */

#define GPIO_FLASH_CS    (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                          GPIO_OUTPUT_SET|GPIO_PORTA|GPIO_PIN15)

/* ===== VL53L0X 传感器引脚 ===== */

/* XSHUT=PC5(输出，拉高使能), GPIO1=PC4(输入，测距完成中断) */

#define GPIO_VL53L0X_XSHUT  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|\
                             GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN5)
#define GPIO_VL53L0X_GPIO1  (GPIO_INPUT|GPIO_PULLUP|GPIO_PORTC|GPIO_PIN4)

/* ===== LD2410B 毫米波雷达 ===== */

/* 人体存在输入: PC0 */

#define GPIO_LD2410B_PRESENCE  (GPIO_INPUT|GPIO_PULLDOWN|GPIO_PORTC|GPIO_PIN0)

/* ===== USB 配置 ===== */

/* USB OTG FS: PA11=DM, PA12=DP */

#endif /* __BOARDS_ARM_STM32_STM32F407_CUSTOM_INCLUDE_BOARD_H */
